version: '2'
services:
    monolithicjwtappdemo-app:
        image: monolithicjwtappdemo
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://monolithicjwtappdemo-mysql:3306/monolithicjwtappdemo?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    monolithicjwtappdemo-mysql:
        extends:
            file: mysql.yml
            service: monolithicjwtappdemo-mysql
